service: javadocs-api

package:
  individually: true

useDotenv: true

plugins:
  - serverless-bundle
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
    APP_NAME: ${env:APP_NAME}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
