service: javadocs-api

package:
  individually: true

useDotenv: true

plugins:
  - serverless-bundle
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
    recipeTable: recipes
    usersTable: usersTable
    jwtSecret: ${env:JWT_SECRET}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  # user functions
  registerUser:
    handler: handlers/users.register
    events:
      - http:
          path: users/register
          method: post
  listUsers:
    handler: handlers/users.list
    events:
      - http:
        path: users/list
        method: get
  # recipe functions
  createRecipe: 
    handler: handlers/recipe.create
    events:
      - http:
          path: recipes/create
          method: post
  getRecipe:
    handler: handlers/recipe.get
    events:
      - http:
          path: recipes/{id}
          method: get
  updateRecipe:
    handler: handlers/recipe.update
    events:
      - http:
          path: recipes/{id}
          method: post
  listRecipes:
    handler: handlers/recipe.list
    events:
      - http:
          path: recipes/
          method: post
  deleteRecipe:
    handler: handlers/recipe.deleteRecipe
    events:
      - http:
          path: recipes/delete/{id}
          method: delete
  